- name: install ngnix
  hosts: practise
  tasks:
  - name: installation of ngnix server
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: starting the nginx service
    ansible.builtin.service:
      name: service
      state: started